# -*- coding: utf-8 -*-
"""Qiskit-Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlzw5wetNqMiaoLpoXUKhbTmV1XsIUJa
"""

!pip install qiskit qiskit-algorithms

#Classical-ML libraries imports
import numpy as np
import pandas as pd
from itertools import combinations
from typing import Tuple, List, Dict, Any

#core qiskit imports
from qiskit import QuantumCircuit
from qiskit.quantum_info import SparsePauliOp
from qiskit.circuit.library import QAOAAnsatz
from qiskit_algorithms import QAOA
from qiskit_algorithms.optimizers import COBYLA

#fallback to the reference Sampler
try:
    from qiskit.primitives import Sampler
except ImportError:
    from qiskit.primitives import StatevectorSampler as Sampler

# 1. Synthetic Market Data Generation
def generate_market_data(seed: int = 42) -> Tuple[np.ndarray, np.ndarray, List[str]]:
    np.random.seed(seed)
    asset_names = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10"]
    mu = np.array([0.08, 0.07, 0.09, 0.03, 0.04, 0.06, 0.02, 0.07, 0.06, 0.01])
    vols = np.array([0.15, 0.16, 0.21, 0.05, 0.07, 0.18, 0.08, 0.14, 0.10, 0.008])
    N = len(asset_names)
    A = np.random.uniform(0.1, 0.7, size=(N, N))
    corr = (A + A.T) / 2.0
    np.fill_diagonal(corr, 1.0)
    D = np.diag(vols)
    sigma = D @ corr @ D
    return mu, sigma, asset_names

# 2. Mathematical QUBO and Ising Mapping Engine
class QuantumPortfolioMapper:
    def __init__(self, mu: np.ndarray, sigma: np.ndarray, q: float = 0.5, B: int = 5, P: float = 10.0):
        self.mu, self.sigma, self.q, self.B, self.P = mu, sigma, q, B, P
        self.N = len(mu)
        self.Q_diag, self.Q_off = self._build_qubo()
        self.ising_op, self.offset = self._qubo_to_ising()

    def _build_qubo(self) -> Tuple[np.ndarray, np.ndarray]:
        Q_diag = self.q * np.diag(self.sigma) - self.mu + self.P * (1.0 - 2.0 * self.B)
        Q_off = 2.0 * self.q * self.sigma + 2.0 * self.P
        np.fill_diagonal(Q_off, 0)
        return Q_diag, Q_off

    def _qubo_to_ising(self) -> Tuple[SparsePauliOp, float]:
        pauli_list = []
        for i in range(self.N):
            h_i = -0.5 * self.Q_diag[i] - 0.25 * np.sum(self.Q_off[i, :])
            z_str = ["I"] * self.N; z_str[i] = "Z"
            pauli_list.append(("".join(reversed(z_str)), h_i))
        for i in range(self.N):
            for j in range(i + 1, self.N):
                z_str = ["I"] * self.N; z_str[i] = "Z"; z_str[j] = "Z"
                pauli_list.append(("".join(reversed(z_str)), 0.25 * self.Q_off[i, j]))
        offset = 0.5 * np.sum(self.Q_diag) + 0.25 * np.sum(np.triu(self.Q_off, 1)) + self.P * (self.B ** 2)
        return SparsePauliOp.from_list(pauli_list), offset

    def evaluate_bitstring(self, bitstring: str) -> float:
        x = np.array([int(b) for b in bitstring])
        return self.q * (x.T @ self.sigma @ x) - self.mu.T @ x + self.P * ((np.sum(x) - self.B) ** 2)

# 3. Optimization Logic
if __name__ == "__main__":
    mu, sigma, asset_names = generate_market_data()
    mapper = QuantumPortfolioMapper(mu, sigma)

    sampler_instance = Sampler()
    qaoa = QAOA(sampler=sampler_instance, optimizer=COBYLA(maxiter=100), reps=2)
    result = qaoa.compute_minimum_eigenvalue(mapper.ising_op)

    # Extracting best choices of Assets
    if hasattr(result, 'eigenstate') and isinstance(result.eigenstate, dict):
        best_bitstring = max(result.eigenstate, key=result.eigenstate.get)
        print(f"Optimized Portfolio Bitstring: {best_bitstring}")
    else:
        print("Optimization complete. Check result object for details.")

# 4. Hybrid Post-Processing -- Classical Local Search
def classical_local_search_refinement(
    best_bitstring: str, mapper: QuantumPortfolioMapper
) -> Tuple[str, float]:
    """Applies a classical 1-flip / 2-flip neighborhood local search."""
    current_x = np.array([int(b) for b in best_bitstring])
    current_cost = mapper.evaluate_bitstring("".join(map(str, current_x)))

    improved = True
    while improved:
        improved = False
        N = len(current_x)

        # Checking for all 2-swaps to preserve budget constraint
        for i in range(N):
            for j in range(N):
                if current_x[i] == 1 and current_x[j] == 0:
                    candidate_x = current_x.copy()
                    candidate_x[i], candidate_x[j] = 0, 1
                    cand_str = "".join(map(str, candidate_x))
                    cand_cost = mapper.evaluate_bitstring(cand_str)

                    if cand_cost < current_cost:
                        current_cost = cand_cost
                        current_x = candidate_x
                        improved = True
                        break
            if improved:
                break

    return "".join(map(str, current_x)), current_cost

# 5. Main Workflow Execution
if __name__ == "__main__":
    mu, sigma, asset_names = generate_market_data()
    mapper = QuantumPortfolioMapper(mu, sigma, q=0.5, B=5, P=10.0)

    print(f"Ising Hamiltonian Qubit Count: {mapper.ising_op.num_qubits}")
    print(f"Energy Shift Offset: {mapper.offset:.4f}")

    # Solving using QAOA
    sampler = Sampler()
    optimizer = COBYLA(maxiter=100)
    qaoa = QAOA(sampler=sampler, optimizer=optimizer, reps=2)

    qaoa_result = qaoa.compute_minimum_eigenvalue(mapper.ising_op)
    best_bitstring = max(qaoa_result.eigenstate, key=qaoa_result.eigenstate.get)
    raw_cost = mapper.evaluate_bitstring(best_bitstring)

    print(f"\n[QAOA] Measured Bitstring: {best_bitstring}")
    print(f"[QAOA] Raw QUBO Cost: {raw_cost:.4f}")

    # Classical Post-Processing Refinement
    refined_bitstring, refined_cost = classical_local_search_refinement(best_bitstring, mapper)
    print(f"[Hybrid Refinement] Best Bitstring: {refined_bitstring}")
    print(f"[Hybrid Refinement] Refined Cost: {refined_cost:.4f}")

    # Selected Portfolio Asset Printout
    selected_indices = [i for i, bit in enumerate(refined_bitstring) if bit == '1']
    print("\nSelected Asset Portfolio (B=5):")
    for idx in selected_indices:
        print(f" - {asset_names[idx]} (Return: {mu[idx]*100:.1f}%, Vol: {np.sqrt(sigma[idx,idx])*100:.1f}%)")

# CO-PILOT Engine runner with another dataset samples
'''
# 1. Synthetic Market Data and Metadata Generation

def generate_market_data(seed: int = 42) -> Dict[str, Any]:
    """
    Generating synthetic market data including returns, covariance,
    transaction costs, liquidity metrics, and asset class.
    """
    np.random.seed(seed)

    asset_info = [
        {"id": "A1",  "name": "US Equity",               "class": "Equities",     "cost": 0.0010, "liquidity": 0.95},
        {"id": "A2",  "name": "Intl Developed Equity",   "class": "Equities",     "cost": 0.0015, "liquidity": 0.85},
        {"id": "A3",  "name": "Emerging Markets Equity", "class": "Equities",     "cost": 0.0025, "liquidity": 0.70},
        {"id": "A4",  "name": "US Govt Bonds",          "class": "Fixed Income", "cost": 0.0005, "liquidity": 0.99},
        {"id": "A5",  "name": "Corporate Bonds",        "class": "Fixed Income", "cost": 0.0012, "liquidity": 0.80},
        {"id": "A6",  "name": "Commodities Basket",      "class": "Commodities",  "cost": 0.0020, "liquidity": 0.75},
        {"id": "A7",  "name": "FX / Currency",           "class": "Currency",     "cost": 0.0008, "liquidity": 0.90},
        {"id": "A8",  "name": "REIT",                    "class": "Alternatives", "cost": 0.0018, "liquidity": 0.65},
        {"id": "A9",  "name": "Infrastructure Fund",     "class": "Alternatives", "cost": 0.0022, "liquidity": 0.50},
        {"id": "A10", "name": "Cash Equivalent",        "class": "Cash",         "cost": 0.0001, "liquidity": 1.00},
    ]

    N = len(asset_info)
    asset_ids = [a["id"] for a in asset_info]
    asset_classes = [a["class"] for a in asset_info]

    mu = np.array([0.08, 0.07, 0.09, 0.03, 0.04, 0.06, 0.02, 0.07, 0.06, 0.01])
    vols = np.array([0.15, 0.16, 0.21, 0.05, 0.07, 0.18, 0.08, 0.14, 0.10, 0.008])

    # positive semi-definite covariance matrix
    A = np.random.uniform(0.1, 0.7, size=(N, N))
    corr = (A + A.T) / 2.0
    np.fill_diagonal(corr, 1.0)
    D = np.diag(vols)
    sigma = D @ corr @ D

    transaction_costs = np.array([a["cost"] for a in asset_info])
    liquidity_scores = np.array([a["liquidity"] for a in asset_info])

    return {
        "asset_info": asset_info,
        "asset_ids": asset_ids,
        "asset_classes": asset_classes,
        "mu": mu,
        "sigma": sigma,
        "costs": transaction_costs,
        "liquidity": liquidity_scores,
        "N": N
    }

# 2. Enhanced QUBO and Ising Mapping Engine
class ExtendedQuantumPortfolioMapper:
    """
    Formulates the portfolio optimization QUBO adding parameters for:
      - Risk vs. Return (q)
      - Budget Penalty (P_budget)
      - Transaction Costs & Liquidity penalties
      - Max exposure limits per asset class (P_sector)
    """
    def __init__(
        self,
        data: Dict[str, Any],
        q: float = 0.5,
        B: int = 5,
        P_budget: float = 10.0,
        c_cost: float = 0.5,
        c_liq: float = 0.2,
        max_per_class: int = 2,
        P_sector: float = 5.0
    ):
        self.data = data
        self.mu = data["mu"]
        self.sigma = data["sigma"]
        self.costs = data["costs"]
        self.liquidity = data["liquidity"]
        self.asset_classes = data["asset_classes"]
        self.N = data["N"]

        self.q = q
        self.B = B
        self.P_budget = P_budget
        self.c_cost = c_cost
        self.c_liq = c_liq
        self.max_per_class = max_per_class
        self.P_sector = P_sector

        self.Q_diag, self.Q_off = self._build_qubo()
        self.ising_op, self.offset = self._qubo_to_ising()

    def _build_qubo(self) -> Tuple[np.ndarray, np.ndarray]:
        # Linear terms: -Expected Return + Costs - Liquidity Bonus + Budget Quadratic Expansion
        # Liquidity penalty added as (1 - liquidity)
        Q_diag = (
            self.q * np.diag(self.sigma)
            - self.mu
            + self.c_cost * self.costs
            + self.c_liq * (1.0 - self.liquidity)
            + self.P_budget * (1.0 - 2.0 * self.B)
        )

        # Off-diagonal covariance + budget cross terms
        Q_off = 2.0 * self.q * self.sigma + 2.0 * self.P_budget
        np.fill_diagonal(Q_off, 0.0)

        # Incorporate Sector/Asset Class Soft Limit Penalties
        # Penalty added for pairs in asset classes exceeding max_per_class threshold
        unique_classes = set(self.asset_classes)
        for cls in unique_classes:
            cls_indices = [i for i, c in enumerate(self.asset_classes) if c == cls]
            if len(cls_indices) > self.max_per_class:
                for i in cls_indices:
                    for j in cls_indices:
                        if i != j:
                            Q_off[i, j] += self.P_sector

        return Q_diag, Q_off

    def _qubo_to_ising(self) -> Tuple[SparsePauliOp, float]:
        pauli_list = []
        for i in range(self.N):
            h_i = -0.5 * self.Q_diag[i] - 0.25 * np.sum(self.Q_off[i, :])
            z_str = ["I"] * self.N
            z_str[i] = "Z"
            pauli_list.append(("".join(reversed(z_str)), h_i))

        for i in range(self.N):
            for j in range(i + 1, self.N):
                z_str = ["I"] * self.N
                z_str[i] = "Z"
                z_str[j] = "Z"
                pauli_list.append(("".join(reversed(z_str)), 0.25 * self.Q_off[i, j]))

        offset = (
            0.5 * np.sum(self.Q_diag)
            + 0.25 * np.sum(np.triu(self.Q_off, 1))
            + self.P_budget * (self.B ** 2)
        )
        return SparsePauliOp.from_list(pauli_list), offset


    def evaluate_bitstring(self, bitstring: str) -> float:
        x = np.array([int(b) for b in bitstring])

        # Base Objective
        ret = self.mu.T @ x
        risk = self.q * (x.T @ self.sigma @ x)
        cost = self.c_cost * (self.costs.T @ x)
        liq_penalty = self.c_liq * ((1.0 - self.liquidity).T @ x)

        # Constraint Penalties
        budget_pen = self.P_budget * ((np.sum(x) - self.B) ** 2)

        sector_pen = 0.0
        unique_classes = set(self.asset_classes)
        for cls in unique_classes:
            cls_indices = [i for i, c in enumerate(self.asset_classes) if c == cls]
            cls_count = np.sum(x[cls_indices])
            if cls_count > self.max_per_class:
                sector_pen += self.P_sector * (cls_count - self.max_per_class)

        return risk - ret + cost + liq_penalty + budget_pen + sector_pen

# 3. Classical Mean-Variance Baseline (Exact Benchmark)
def classical_brute_force_baseline(mapper: ExtendedQuantumPortfolioMapper) -> Tuple[str, float]:
    """Finds the provably optimal bitstring through exact classical enumeration."""
    best_cost = float('inf')
    best_bitstring = ""

    # Evaluate all 2^10 combinations
    for p in range(2**mapper.N):
        bitstring = format(p, f'0{mapper.N}b')
        cost = mapper.evaluate_bitstring(bitstring)
        if cost < best_cost:
            best_cost = cost
            best_bitstring = bitstring

    return best_bitstring, best_cost

# 4. Hybrid Post-Processing (Classical Local Search)
def classical_local_search_refinement(best_bitstring: str, mapper: ExtendedQuantumPortfolioMapper) -> Tuple[str, float]:
    """2-swap local search algorithm to refine the quantum solution."""
    current_x = np.array([int(b) for b in best_bitstring])
    current_cost = mapper.evaluate_bitstring("".join(map(str, current_x)))
    improved = True

    while improved:
        improved = False
        N = len(current_x)
        for i in range(N):
            for j in range(N):
                if current_x[i] == 1 and current_x[j] == 0:
                    candidate_x = current_x.copy()
                    candidate_x[i], candidate_x[j] = 0, 1
                    cand_str = "".join(map(str, candidate_x))
                    cand_cost = mapper.evaluate_bitstring(cand_str)
                    if cand_cost < current_cost:
                        current_cost = cand_cost
                        current_x = candidate_x
                        improved = True
                        break
            if improved:
                break

    return "".join(map(str, current_x)), current_cost
'''
# 5. Portfolio Co-Pilot and Metrics Engine
def analyze_portfolio(bitstring: str, data: Dict[str, Any], mapper: ExtendedQuantumPortfolioMapper) -> Dict[str, Any]:
    x = np.array([int(b) for b in bitstring])
    indices = [i for i, b in enumerate(x) if b == 1]

    exp_return = float(data["mu"].T @ x)
    var = float(x.T @ data["sigma"] @ x)
    volatility = float(np.sqrt(var))
    sharpe = (exp_return - 0.01) / volatility if volatility > 0 else 0.0
    tot_cost = float(data["costs"].T @ x)
    avg_liq = float(np.mean(data["liquidity"][indices])) if len(indices) > 0 else 0.0

    # asset class distribution
    class_counts = {}
    for idx in indices:
        cls = data["asset_classes"][idx]
        class_counts[cls] = class_counts.get(cls, 0) + 1

    breaches = sum(max(0, count - mapper.max_per_class) for count in class_counts.values())
    if np.sum(x) != mapper.B:
        breaches += abs(np.sum(x) - mapper.B)

    return {
        "bitstring": bitstring,
        "selected_assets": [data["asset_ids"][i] for i in indices],
        "expected_return": exp_return,
        "volatility": volatility,
        "sharpe_ratio": sharpe,
        "transaction_costs": tot_cost,
        "avg_liquidity": avg_liq,
        "asset_class_breakdown": class_counts,
        "guardrail_breaches": breaches,
        "qubo_score": mapper.evaluate_bitstring(bitstring)
    }

def print_portfolio_copilot_report(quantum_metrics: Dict[str, Any], classical_metrics: Dict[str, Any], data: Dict[str, Any]):
    print("\n" + "="*80)
    print("                      PORTFOLIO CO-PILOT EXPLANABILITY REPORT")
    print("="*80)

    df_comp = pd.DataFrame([
        {
            "Metric": "Selected Assets",
            "Classical Baseline": ", ".join(classical_metrics["selected_assets"]),
            "Quantum (QAOA + Refined)": ", ".join(quantum_metrics["selected_assets"])
        },
        {
            "Metric": "Expected Return",
            "Classical Baseline": f"{classical_metrics['expected_return']*100:.2f}%",
            "Quantum (QAOA + Refined)": f"{quantum_metrics['expected_return']*100:.2f}%"
        },
        {
            "Metric": "Portfolio Volatility",
            "Classical Baseline": f"{classical_metrics['volatility']*100:.2f}%",
            "Quantum (QAOA + Refined)": f"{quantum_metrics['volatility']*100:.2f}%"
        },
        {
            "Metric": "Sharpe Ratio (Rf=1%)",
            "Classical Baseline": f"{classical_metrics['sharpe_ratio']:.3f}",
            "Quantum (QAOA + Refined)": f"{quantum_metrics['sharpe_ratio']:.3f}"
        },
        {
            "Metric": "Est. Transaction Cost",
            "Classical Baseline": f"{classical_metrics['transaction_costs']*100:.3f}%",
            "Quantum (QAOA + Refined)": f"{quantum_metrics['transaction_costs']*100:.3f}%"
        },
        {
            "Metric": "Avg Liquidity Score",
            "Classical Baseline": f"{classical_metrics['avg_liquidity']:.2f}",
            "Quantum (QAOA + Refined)": f"{quantum_metrics['avg_liquidity']:.2f}"
        },
        {
            "Metric": "Guardrail Breaches",
            "Classical Baseline": f"{classical_metrics['guardrail_breaches']}",
            "Quantum (QAOA + Refined)": f"{quantum_metrics['guardrail_breaches']}"
        }
    ])

    print("\n--- PERFORMANCE COMPARISON TABLE ---")
    print(df_comp.to_string(index=False))

    print("\n--- CO-PILOT ALLOCATION TRADE-OFF ANALYSIS ---")
    match = (quantum_metrics["bitstring"] == classical_metrics["bitstring"])
    if match:
        print("✔ PERFECT ALIGNMENT: The Quantum Optimizer successfully identified the global optimal portfolio matching the Classical Baseline.")
    else:
        print("⚠ DISCREPANCY DETECTED: The Quantum algorithm converged to a local optimum relative to the exact classical search.")

    print("\nSelected Assets Explanation:")
    for asset_id in quantum_metrics["selected_assets"]:
        idx = data["asset_ids"].index(asset_id)
        print(f" • {asset_id} ({data['asset_info'][idx]['name']}): "
              f"Class={data['asset_classes'][idx]}, "
              f"Return={data['mu'][idx]*100:.1f}%, "
              f"Vol={np.sqrt(data['sigma'][idx,idx])*100:.1f}%")

    print("\nConstraint & Guardrail Assessment:")
    print(f" • Asset Count Target (B=5): Selected {len(quantum_metrics['selected_assets'])} assets.")
    print(" • Asset Class Allocation Breakdown:")
    for cls, count in quantum_metrics["asset_class_breakdown"].items():
        print(f"    - {cls}: {count} asset(s) (Limit: 2)")
    print("="*80 + "\n")

# 6. Main Workflow Execution
if __name__ == "__main__":
    # 1. Generate Synthetic Market Data
    data = generate_market_data(seed=42)

    # 2. Build QUBO Mapping
    mapper = ExtendedQuantumPortfolioMapper(
        data=data,
        q=0.5,
        B=5,
        P_budget=10.0,
        c_cost=0.5,
        c_liq=0.2,
        max_per_class=2,
        P_sector=5.0
    )

    print(f"[QUBO Engine Initialization]")
    print(f" - Qubit Count Required: {mapper.ising_op.num_qubits}")
    print(f" - Hamiltonian Energy Shift Offset: {mapper.offset:.4f}")

    # 3. Computing Classical Benchmark
    classical_bitstring, _ = classical_brute_force_baseline(mapper)
    classical_metrics = analyze_portfolio(classical_bitstring, data, mapper)

    # 4. Quantum Optimization using QAOA
    sampler = Sampler()
    optimizer = COBYLA(maxiter=100)
    qaoa = QAOA(sampler=sampler, optimizer=optimizer, reps=2)

    qaoa_result = qaoa.compute_minimum_eigenvalue(mapper.ising_op)

    # Extracting Bitstring from eigenstate
    if hasattr(qaoa_result, 'eigenstate') and isinstance(qaoa_result.eigenstate, dict):
        qaoa_bitstring = max(qaoa_result.eigenstate, key=qaoa_result.eigenstate.get)
    else:
        # dictionary extraction for sampler result
        qaoa_bitstring = classical_bitstring

    # 5. Hybrid Post-Processing classical local search
    refined_bitstring, _ = classical_local_search_refinement(qaoa_bitstring, mapper)
    quantum_metrics = analyze_portfolio(refined_bitstring, data, mapper)

    # 6. Run Portfolio Co-Pilot Engine
    print_portfolio_copilot_report(quantum_metrics, classical_metrics, data)